# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URVERSION = $(shell urweb -version)
.PHONY: all
all: ./Detach.db ./Detach.exe ./Detach.sql ./Makefile
./Detach.db: ./Detach.exe ./Detach.sql ./Makefile
	dropdb --if-exists Detach
	createdb Detach
	psql -f ./Detach.sql Detach
	touch ./Detach.db
./Detach.exe: .fix-multy1
./Detach.urp: ./Detach.ur ./Detach.urs ./Makefile ./urweb-callback/lib.urp .cake3/tmpDetach.in0
	cat .cake3/tmpDetach.in0 > ./Detach.urp
.cake3/tmpDetach.in0: ./Makefile
	-rm -rf .cake3/tmpDetach.in0
	echo 'debug' >> .cake3/tmpDetach.in0
	echo 'allow mime text/javascript' >> .cake3/tmpDetach.in0
	echo 'allow mime text/css' >> .cake3/tmpDetach.in0
	echo 'allow mime image/jpeg' >> .cake3/tmpDetach.in0
	echo 'allow mime image/png' >> .cake3/tmpDetach.in0
	echo 'allow mime image/gif' >> .cake3/tmpDetach.in0
	echo 'allow mime application/octet-stream' >> .cake3/tmpDetach.in0
	echo 'safeGet Detach/C/callback' >> .cake3/tmpDetach.in0
	echo 'safeGet Detach/download' >> .cake3/tmpDetach.in0
	echo 'database dbname=Detach' >> .cake3/tmpDetach.in0
	echo 'library ./urweb-callback' >> .cake3/tmpDetach.in0
	echo 'sql ./Detach.sql' >> .cake3/tmpDetach.in0
	echo '' >> .cake3/tmpDetach.in0
	echo './Detach' >> .cake3/tmpDetach.in0
./Detach.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: ./Detach.urp ./Makefile $(call GUARD,URVERSION)
	urweb -dbms postgres ./Detach
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: ./Detach.db
./Detach.db: .fix-multy1
.PHONY: ./Detach.exe
./Detach.exe: .fix-multy1
.PHONY: ./Detach.urp
./Detach.urp: .fix-multy1
.PHONY: .cake3/tmpDetach.in0
.cake3/tmpDetach.in0: .fix-multy1
.PHONY: ./Detach.sql
./Detach.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -C ./urweb-callback -f Makefile 
	MAIN=1 $(MAKE) -f ./Makefile $(MAKECMDGOALS)

endif
.PHONY: clean
clean: 
	-rm ./Detach.db ./Detach.exe ./Detach.sql ./Detach.urp .cake3/tmpDetach.in0
	-rm -rf .cake3

endif
